### ISSUE TITLE
fix birthdayAnnouncements method

### ISSUE THREAD

**Issue by dankrzeminski32** [dankrzeminski32/BirthdayDiscordBot#38]
Current Situation:

- birthdayAnnouncements() sends bday message for registered users only in the guild they registered in
- birthdayAnnouncements() will not send announcements in guilds with bday bot and registered user **if** the user **did not** register in that guild

Expected Situation:

- birthdayAnnoucements() should send bday messages for any registered users in any guilds with the bday bot and registered users in them.

**Comment by EthanKvachkoff** [comment]
Note: Associate the Discord_ID with birthdays and then parse all members in each guild and match the Discord_Id to the people with birthdays.

**Comment by dankrzeminski32** [comment]
@EthanKvachkoff I know you mentioned you were working on this, I am going to tag you on this.
