### ISSUE TITLE
Organize + Project Clean up

### ISSUE THREAD

**Issue by EthanKvachkoff** [dankrzeminski32/BirthdayDiscordBot#41]
Current situation:

REAME.md is messy.
Re-used code in most functions, make reference methods. 

Expected situation/ideas:
Reduce file size's
Have the project organized(get rid of useless classes/files)
No more un used imports.

**Comment by dankrzeminski32** [comment]
Could probably break this down into multiple different issues...

But I linked a PR which updates the README file :)
