### ISSUE TITLE
Adding @dataclasses

### ISSUE THREAD

**Issue by EthanKvachkoff** [dankrzeminski32/BirthdayDiscordBot#48]
Current:
We have a bunch of classes that use __init__ and __repr__ which create instance variables. 

Expect:
Import and use Dataclasses which in turn makes it so you dont need the __init__ and __repr__. It does it for you. you just have to name the instance variables below the class

EX:
@dataclass
class Test: 
name: str
id: int

Reason:
Cuts the amount of lines in each file down a tad.

**Comment by dankrzeminski32** [comment]
Made some comments on the PR, not sure if we need dataclass there since those classes don't really represent data structures? 

Open for conversation though...
